name: sbom
description: A Software Bill of Materials generator specifically for Dart packages.
version: 1.0.2
homepage: https://github.com/shamblett/sbom

environment:
 sdk: '>=2.15.0 <3.0.0'

dependencies:
 path: '^1.8.0'
 meta: '^1.7.0'
 args: '^2.3.0'
 yaml: '^3.1.0'
 crypto: '^3.0.1'
 pub_cache: '^0.3.1'

executables:
 sbom:

dev_dependencies:
 lints: '^1.0.1'
 test: '^1.17.12'





