name: sbom
description: A Software Bill of Materials generator for Dart packages.
version: 1.0.0
homepage: https://github.com/shamblett/sbom

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 path: '^1.8.0'
 meta: '^1.7.0'
 args: '^2.3.0'

dev_dependencies:
 pedantic: '^1.11.0'





