name: sbom
description: A Software Bill of Materials generator specifically for Dart packages.
version: 1.0.4
repository: https://github.com/shamblett/sbom
homepage: https://github.com/shamblett/sbom

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=2.15.0 <3.0.0'

dependencies:
 path: '^1.8.2'
 meta: '^1.8.0'
 args: '^2.3.1'
 yaml: '^3.1.1'
 crypto: '^3.0.2'
 pub_cache: '^0.3.1'

executables:
 sbom:

dev_dependencies:
 dart_code_metrics: '^4.17.0'
 lints: '^2.0.0'
 test: '^1.17.12'





